### ISSUE TITLE
Bug in Dropout Example

### ISSUE THREAD

**Issue by rennne** [PacktPublishing/Java-Deep-Learning-Essentials#1]
When I add a HiddenLayer it does not work anymore.
for example:
        int[] hiddenLayerSizes = {100, 100, 80};
in Dropout.java

results in 
Accuracy: 33,3 %
Precision:
 class 1: NaN %
 class 2: 33,3 %
 class 3: NaN %
Recall:
 class 1: 0,0 %
 class 2: 100,0 %
 class 3: 0,0 %

Since I am learning about Neuronal Nets i was not able to fix that bug yet.
Any Help would be appreciated.

**Comment by techsachinkumar** [comment]
Hi rennne

Could you give us clarity in which chapter and which code you are facing this issue?
Please reopen the issue if you got the same problem.

Regards
